### ISSUE TITLE
System.OverflowException: Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by Yannic92** [doxakis/HdbscanSharp#1]
I'm getting the following exception:

> System.OverflowException occurred
  HResult=-2146233066
  Message=Der Wert für einen Int32 war zu groß oder zu klein.
  Source=mscorlib
  StackTrace:
       bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
  InnerException: 

The exception occurred [in this line:](https://github.com/doxakis/HdbscanSharp/blob/master/HdbscanSharp/Hdbscanstar/HdbscanAlgorithm.cs#L589)

	int label = int.Parse(lineContents[i]);

After debugging a bit I found out that there are original doubles appended to `hierarchyWriter`
[in this line:](https://github.com/doxakis/HdbscanSharp/blob/b9eb335aa6bea5019e070dbdcfaf5f64f6dfdfcc/HdbscanSharp/Hdbscanstar/HdbscanAlgorithm.cs#L397)

I think the problem is a Locale problem because in germany for example the decimal delimiter is a comma.
I.E. the following code will result in output to be `"48,91321404939,"`
 
    var currentEdgeWeight = 48.91321404939
    string output = currentEdgeWeight + "" + delimiter;

Possible fix could be:

    NumberFormatInfo nfi = new NumberFormatInfo();
    nfi.NumberDecimalSeparator = ".";
    int outputLength = 0;
    string output = currentEdgeWeight.ToString(nfi) + delimiter;
    hierarchyWriter.Append(output);

**Comment by doxakis** [comment]
The Pull request has been merged.

I uploaded a new version on nuget.

Thanks!
