### ISSUE TITLE
Weights for data points

### ISSUE THREAD

**Issue by ac-en** [doxakis/HdbscanSharp#10]
Is it possible to use weights for data points?
I currently add duplicates to create "weights" for my data points. Seems very inefficient. Is there a better way to do it?

**Comment by doxakis** [comment]
Hi,

I'm not sure if it will work, but one way you could try is by creating a new distance function.

You can see many examples here:
https://github.com/doxakis/HdbscanSharp/tree/master/HdbscanSharp/Distance

There are in fact many distance functions I could have implemented.
This issue list some that are implemented in one python library: https://github.com/doxakis/HdbscanSharp/issues/6

Thanks

**Comment by ac-en** [comment]
EDIT: Solved. It can be done by calculating the distance matrix. Just one entry per identical data point and for the distances the value is distance/(weight of datapoint) instead of distance
Issue can be closed
