### ISSUE TITLE
Provide PDB-Files in nuget package

### ISSUE THREAD

**Issue by Yannic92** [doxakis/HdbscanSharp#3]
Would you mind providing the pdb-files in the nuget package? 

Everytime I need to debug something,  I clone your project and build it on command line to use this dll / pdb.
Since this library is open source it would be nice to be able to debug easily.

I'm not a .NET expert and maybe there are easier ways to debug.
If there is a reason to not provide pdb-files in nuget packages, I would like to learn them.

Thank you for your work :)

**Comment by doxakis** [comment]
Hi,

Good question!

I have done some research.. not sure if it's the perfect way to do it.
Anyway, here is what I have done and it works on Visual Studio 2017.

But, first, I had to modify the way the nuget package is created.

I develop a small script:
https://github.com/doxakis/HdbscanSharp/blob/master/deploy-nuget-version.cmd

Locally, I created a new project: Console App (.NET Core) to test the setup.
In the Package Manager Console, run: `Install-Package HdbscanSharp -Version 1.0.9`

After, I followed the steps on this article : http://geeklearning.io/how-to-debug-a-net-core-nuget-package/

For posterity, the steps:
- Go to Tools -> Options -> Debugger -> General.
- Uncheck “Enable Just My Code (Managed only)”.
- Uncheck “Enable .NET Framework source stepping”. Yes, it is misleading, but if you don't, then Visual Studio will ignore your custom server order (see further on).
- Check “Enable source server support”.
- Uncheck “Require source files to exactly match the original version”
- Go to Tools -> Options -> Debugger -> Symbols.
- Select a folder for the local symbol/source cache.

At the last step, I checked the Microsoft Symbol Servers.

![screenshot](https://user-images.githubusercontent.com/5766482/34242268-80ecdeec-e5e8-11e7-9b38-1ce9b5be54fc.png)

**Comment by Yannic92** [comment]
Hi, 
Thank you for the detailed explanation.
I tried the steps you provided and it seems that it SHOULD work. 
Unfortunately i only have a file named download.error inside $symbol_cache_directory/sym/HdbscanSharp.pdb/$somerRandomTempDirectoryName$.

I will try to find out whats the problem and give you feedback. (I use Visual Studio 2015)

**Comment by doxakis** [comment]
Hi, I will close the issue for now. Feel free to open it again.
