### ISSUE TITLE
Result differs from python variant

### ISSUE THREAD

**Issue by Yannic92** [doxakis/HdbscanSharp#4]
Hi,
I've another question regarding your library.
Doing the following in python: 

```py
import hdbscan

clusterer = hdbscan.HDBSCAN(min_cluster_size=100, core_dist_n_jobs=1)
labels = clusterer.fit_predict(data)
```

should be equal to the following call to your library in c#. Is this assumption correct?
```c#
var parameters = new HdbscanParameters()
{
  DataSet = dataToCluster.RawData,
  MinClusterSize = 100,
  MinPoints = 100,
  DistanceFunction = new EuclideanDistance(),
};
var hdbscanResult = HdbscanRunner.Run(parameters);
```

When visualizing the cluster results using T-SNE the result of the python library you mentioned in your README looks like this:

![figure_4-1](https://user-images.githubusercontent.com/5593674/34616969-26a43eb8-f23a-11e7-915f-b27b4cf132bd.png)

When doing the same with the result the call to your library in the above snippet it looks like this:

![figure_2-2](https://user-images.githubusercontent.com/5593674/34617005-44d9eb58-f23a-11e7-9e39-7fb1826be5df.png)

I wonder about the three (in my opinion) obvious clusters.
Is my call to your library wrong? 
I didn't really understand what the parameter "MinPoints" is used for. 
When does it make sense to initialize this parameter different to MinClusterSize?

**Comment by doxakis** [comment]
Hi,

I didn't compare it to hdbscan (python package)
I had done some tests with the Iris dataset and it gave me acceptable result.
So, I didn't make other tests.
It was a port from a java implementation.

You are right. It's strange..

Can you provide the dataset you use to check what happen ?

I think MinPoints is similar to the parameter min_samples.
(http://hdbscan.readthedocs.io/en/latest/parameter_selection.html?highlight=min_samples#selecting-min-samples)

Thanks!

**Comment by Yannic92** [comment]
Oh thats embarrassing.
In the python variant I did  perform a PCA to 2 dimensions to speed it up.
When calling your library I did not.
Without performing this additional PCA, the python variant results in the same.

I'm really sorry that I bothered you with that.
Thank you for the link explaining MinPoints, this helped me :)

**Comment by doxakis** [comment]
I understand. No problem!

Thank you for having spent time checking and comparing. I appreciate it. 

I don't know on what you are working on. But, if you want to code it in C#, the Accord.NET Framework can do PCA and you can check the "DocumentClusteringExample" example.
