### ISSUE TITLE
OutlierScore calculation problem

### ISSUE THREAD

**Issue by Panaetius** [doxakis/HdbscanSharp#5]
When getting the outlier scores for a clustering, I'm currently getting values between -4 and slightly above one (e.g. 1.00000053). But it is my understanding (and the way the python library behaves) that the outlier score should be between 0.0 and 1.0 .

The values above 1.0 might be due to rounding errors, but the negative values seem wrong.

Looking into the implementation, in the file HdbscanSharp/Hdbscanstar/HdbscanAlgorithm.cs on line 625, you have `score = 1 - (epsilon_max / epsilon);`, whereas the python implementation in the file /hdbscan/_hdbscan_tree.pyx on line 577 has `result[point] = (lambda_max - lambda_array[n]) / lambda_max`, which is the equivalent of `result[point] = 1 - (lambda_array[n]/ lambda_max)` (with `epsilon_max` and `lambda_max` both being the lowest death level). So to me it looks like the c# implementation switched the denominator and numerator, leading to wrong results.

Or are the scores in this implementation meant to be different from the python one?

**Comment by doxakis** [comment]
Hi,

It's strange. I'm curious how you get those results.

It was a port from a java implementation.
So, results may differ.
In fact, it is not based on the python package.
But overall, results should be similar.

When I'm running IrisDatasetExample, all outlier score are between 0 and 1.

The following line: score = 1 - (epsilon_max / epsilon);
can be rewritten as : score = (epsilon - epsilon_max) / epsilon;

But the following : score = (epsilon_max - epsilon) / epsilon_max;
doesn't seem to work for the IrisDatasetExample.

I feel limited. Maybe you can try changing the score formula or you can provide an example. So I can reproduce it.

**Comment by Panaetius** [comment]
Sorry for the delayed response, it was a pretty busy week.

I managed to narrow it down and it's a bug/numerical instability in the PearsonCorrelation distance function.

Specifically, the two dataseries:

`new double[] { 21.33, 21.33, 21.33, 21.33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}`
`new double[] { 19.99, 19.99, 19.99, 19.990000000000002, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },`

Will lead to a correlation bigger than 1 (1.0000000000002), and when that is subtracted from 1 in PearsonCorrelation.cs line 34, it results in a distance smaller 1, which in turn leads to negative child death levels. And those can result in epsilon and epsilon_max values that, when divided by each other, are bigger than 1, giving a negative outlier score.

A quick and simple fix would be to just change the correlation calculation to never be higher than 1 with a min, though I'm not sure how that would impact performance.

E.g.:

`return (1 - Math.Min(covariance / Math.Sqrt(standardDeviationOne * standardDeviationTwo), 1));`


The same is true with negative correlation, so a `Math.Max` with -1 is also needed, though this doesn't show up in my dataset (I could reproduce it by negating one of the series mentioned above)


Maybe [this](https://stats.stackexchange.com/questions/235004/is-it-possible-to-have-pearson-correlation-coefficient-values-1-or-values-1) SO answer can help implement a numerically stable calculation, but for my purposes, just using Min/Max is fine for now and I lack the time to fix it properly.

Thanks for you help and great library!

**Comment by doxakis** [comment]
Hi,

No problem.

Hmmm, I would suggest to use:
return Math.Max(0, (1 - (covariance / Math.Sqrt(standardDeviationOne * standardDeviationTwo))));

It will evaluate the final result and make correction if applicable.

So, the distance is always greater than or equals to 0 and this can prevent negative child death levels.
I don’t think we need to add another check. It would not cause problem that the number is slightly greater than 2.

The Cosine Similarity distance seem to be also affected and I would add similar logic to prevent the issue.

What do you think ?

If it is ok with you, I can make changes and deploy a new version to NuGet.

Thanks!

**Comment by Panaetius** [comment]
I think that makes sense. 

You're probably right that values that are too big don't lead to the error in question and a correction for that isn't necessary.

A new version on Nuget would be great, then we wouldn't have to include the whole source in our project.

**Comment by doxakis** [comment]
Hi,

I uploaded a new version on Nuget.

`Install-Package HdbscanSharp -Version 1.0.10`

If you want to implement a custom distance function, you can create a new class on your project which implements IDistanceCalculator. So, you can use the Nuget package while being able to customize it for your use case.

In order to prevent the issue again, I created a unit test project.

Thanks again :)
