### ISSUE TITLE
.NET Standard?

### ISSUE THREAD

**Issue by myrabyte** [doxakis/HdbscanSharp#7]
This is an awesome library!

But are there any plans to make it support .NET standard?  Or is it a dependency on Accord?

**Comment by doxakis** [comment]
Hi,

Thanks!

The project HdbscanSharp does not depend on any package. So, it should be as simple as adding `netstandard2.0` in the `TargetFrameworks` (file: HdbscanSharp/HdbscanSharp.csproj) and updating the nuget package.

I will do it in the next following days.

**Comment by doxakis** [comment]
Hi,

It supports .NET standard 2.0 now.
I uploaded a new version on Nuget.

Thanks!
