### ISSUE TITLE
Assembly is not strong-named

### ISSUE THREAD

**Issue by pedropaulovc** [doxakis/HdbscanSharp#8]
**Repro steps:**

1. Download the latest version from NuGet
2. Unpack the `.nupkg` file
3. Run `sn -vf HdbscanSharp.1.0.15\lib\net45\HdbscanSharp.dll`

**Expected:**
The `sn.exe` tool would output 

```
Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'HdbscanSharp.1.0.15\lib\net45\HdbscanSharp.dll' is valid
```

**Actual:**
The `sn.exe` tool outputs

```
Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

HdbscanSharp.1.0.15\lib\net45\HdbscanSharp.dll does not represent a strongly named assembly
```

**Observation:**
This blocks strong-named .NET assemblies from depending on `HdbscanSharp`. See [Why strong-name your assemblies?](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies)

**Comment by doxakis** [comment]
Hi,

Good catch. I was not aware of that.

I merged the commit and release a new nuget version.

Thanks!
